### ISSUE TITLE
Password input insecure

### ISSUE THREAD

**Issue by mwiens91** [csvenja/SFU-iCalendar#14]
In Firefox 53.0, a tooltip appears alerting the user that their password could be compromised:

![Screencap](https://cloud.githubusercontent.com/assets/5615055/25364247/e80ace58-2915-11e7-86b1-04606f828868.png)

Obviously this is concerning, and ought to be corrected should this project still be active.

**Comment by xhacker** [comment]
Hi, the web server doesn’t support HTTPS yet. That’s why you got the warning. You can use the command line tool if you feel concerning.

**Comment by mwiens91** [comment]
Ah, I see. Fair enough.
